apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-jenkins-app
  labels:
    app: demo-jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-jenkins-app
  template:
    metadata:
      labels:
        app: demo-jenkins-app
    spec:
      serviceAccountName: cicd-dev
      containers:
        - name: demo_jenkins_app
          image: 10.10.3.225:30002/demos/demo_jenkins:2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
